### ISSUE TITLE
replace audio files

### ISSUE THREAD

**Issue by sballe73** [entropia/tip-toi-reveng#121]
Hi,
Replacing audio files in gme file sometime is refused because you have data after the audio section.
If we manage to make an ogg file of lesser size that the original one, do you think it could work to replace the original after padding it with zeros ?

**Comment by uli42** [comment]
On Mon, Dec 28, 2015 at 5:21 PM, sballe73 <notifications@github.com> wrote:
> Replacing audio files in gme file sometime is refused because you have data after the audio section
> If we manage to make an ogg file of lesser size that the original one, do you think it could work to replace the original after padding it with zeros ?

Yes, I don't see why this should not work. But this is only necessary
temporarily until we can do roundtripping (dump the games to the yaml
file and read them from there)

Uli

**Comment by nomeata** [comment]
>  Replacing audio files in gme file sometime is refused because you have data after the audio section

This sounds as if you are using `libtiptoi.c`. This is old and unmaintained, I’m not sure if we should still carry that in the code.

**Comment by sballe73** [comment]
yes, I used libtiptoi.c

I bought a tiptoi for my kids and was looking on how to install new games from linux computer. Then found your stuff wich is real work.
Saw your video wich is advanced hack :)
Had a look at the haskell tuto while tttools was installing/compiling.
Nice.

So I just wondered if I could easily replace a few sounds in the book I just bought to make the kids have fun  as of course my own fun doesn't count.

**Comment by nomeata** [comment]
I recommend that you use tttool. Until we fixed the round-tripping of games, what you can do is: When replacing the sounds, change the `product-id` in the `YAML` file and print a separate start code for your modified version. Then put the gme file next to the existing on on the pen, this way your kids can even choose which version they want to use.

**Comment by nomeata** [comment]
(There does not seem to be anything to do for this tickets, so i’m closing it. Please re-open if you disagree.)

**Comment by sballe73** [comment]
Yes, I am still not able to do what I want but I have not read all your doc still. So I will come back later if needed.
Thanks
